This project is for Spring testing purposes only, creating a "`Hello, World`" RESTful web.

== What it's build
Service that will accept HTTP GET requests at
`http://localhost:8080/world`.

It will respond with a JSON representation of a worl, as the following listing shows:

====
[source,json]
----
{"id":1,"message":"Hello World!"}
----
====

== Spring dependencies

The following listing shows the `pom.xml` file that is created when you choose Maven:

====
[source,xml]
----
include::initial/pom.xml[]
----
====


[[initial]]
== Resource Representation Class
The service will handle `GET` requests for `/world`. The `GET` request should return a `200 OK` response with JSON in the
body that represents a greeting. It should resemble the following output:

====
[source,json]
----
{
    "id": 1,
    "message": "Hello World!"
}
----
====

The `id` field is a unique identifier for the world, and `message` is the textual
representation of the world.

Model the world representation, is created a resource representation class. Provided a plain old Java object with fields, constructors, and accessors for the `id` and
`message` data, as the following listing (from
`src/main/java/com/viktor/controller/World`) shows:

[source,java]
----
include::complete/src/main/java/com/viktor/model/World.java[]
----

====
NOTE: This application uses the https://github.com/FasterXML/jackson[Jackson JSON] library to
automatically marshal instances of type `World` into JSON. Jackson is included by default by the web starter.
====

== Resource Controller

In Spring's approach to building RESTful web services, HTTP requests are handled by a
controller. These components are identified by the
https://docs.spring.io/spring/docs/{spring_version}/javadoc-api/org/springframework/web/bind/annotation/RestController.html[`@RestController`]
annotation, and the `WorldController` shown in the following listing (from
`src/main/java/com/viktor/controller/WorldController.java`) handles `GET` requests
for `/world` by returning a new instance of the `World` class:

====
[source,java]
----
include::complete/src/main/java/com/viktor/controller/WorldController.java[]
----
====

This controller is concise and simple, but there is plenty going on under the hood. We
break it down step by step.

The `@GetMapping` annotation ensures that HTTP GET requests to `/world` are mapped to the `world()` method.

NOTE: There are companion annotations for other HTTP verbs (e.g. `@PostMapping` for POST). There is also a `@RequestMapping` annotation that they all derive from, and can serve as a synonym (e.g. `@RequestMapping(method=GET)`).

The implementation of the method body creates and returns a new `World` object with
`id` and `message` attributes based on the next value from the `counter by using the world `template`.

A key difference between a traditional MVC controller and the RESTful web service
controller shown earlier is the way that the HTTP response body is created. Rather than
relying on a view technology to perform server-side rendering of the greeting data to
HTML, this RESTful web service controller populates and returns a `World` object. The
object data will be written directly to the HTTP response as JSON.

This code uses Spring
https://docs.spring.io/spring/docs/{spring_version}/javadoc-api/org/springframework/web/bind/annotation/RestController.html[`@RestController`]
annotation, which marks the class as a controller where every method returns a domain
object instead of a view. It is shorthand for including both `@Controller` and
`@ResponseBody`.

The `World` object must be converted to JSON. Thanks to Spring's HTTP message converter
support, you need not do this conversion manually. Because
https://github.com/FasterXML/jackson[Jackson 2] is on the classpath, Spring's
https://docs.spring.io/spring/docs/{spring_version}/javadoc-api/org/springframework/http/converter/json/MappingJackson2HttpMessageConverter.html[`MappingJackson2HttpMessageConverter`]
is automatically chosen to convert the `World` instance to JSON.


Logging output is displayed. The service should be up and running within a few seconds.


== Test the Service

When service is up, visit `http://localhost:8080/world`, where you should see:

====
[source,json]
----
{"id":1,"message":"Hello World!"}
----
====


This change demonstrates that the `@RequestParam` arrangement in `WorldController` is
working as expected.

Notice also how the `id` attribute has changed from `1` to `2`. This proves that you are
working against the same `WorldController` instance across multiple requests and that
its `counter` field is being incremented on each call as expected.
